apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpMetricsWatcher.fullname" . }}
  labels:
    {{- include "cpMetricsWatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cpMetricsWatcher.service.type }}
  ports:
    - port: {{ .Values.cpMetricsWatcher.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cpMetricsWatcher.selectorLabels" . | nindent 4 }}
