{{ if .Values.cpMetricsWatcher.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cpMetricsWatcher.fullname" . }}
  labels:
    {{- include "cpMetricsWatcher.labels" . | nindent 4 }}
  {{- with .Values.cpMetricsWatcher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
