global:
  temboEnabled: true
  monitoringEnabled: false
  conductorEnabled: false
  baseDomain: ~
tembo:
  conductor:
    env:
      - name: PG_CONN_URL
        valueFrom:
          secretKeyRef:
            name: control-plane-connection
            key: rw_uri
      - name: POSTGRES_QUEUE_CONNECTION
        valueFrom:
          secretKeyRef:
            name: control-plane-queue-connection
            key: rw_uri
      - name: CONTROL_PLANE_EVENTS_QUEUE
        value: "saas_queue"
      - name: DATA_PLANE_EVENTS_QUEUE
        value: "data_plane_events"
      - name: DATA_PLANE_BASEDOMAIN
        value: ~
      - name: BACKUP_ARCHIVE_BUCKET
        value: "tembo-backups"
      - name: CF_TEMPLATE_BUCKET
        value: "tembo-cf-templates"
      - name: METRICS_EVENTS_QUEUE
        value: "metrics_events"
      - name: IS_CLOUD_FORMATION
        value: "false"
      - name: PROMETHEUS_URL
        value: "http://tembo-kube-prometheus-stac-prometheus.tembo.svc.cluster.local:9090"
  tembo-operator:
    controller:
      monitoring:
        prometheusRule:
          enabled: true
        podMonitor:
          enabled: true
          port: http
          path: /metrics
      extraEnv:
        - name: DATA_PLANE_BASEDOMAIN
          value: ~
    cloudnative-pg:
      monitoring:
        podMonitorEnabled: true
  cpWebserver:
    env:
      - name: CLERK_SECRET_KEY
        value: ~
      - name: CLERK_WEBHOOK_SIGNING_SECRET
        value: ~
      - name: STRIPE_SECRET_KEY
        value: ~
      - name: STRIPE_WEBHOOK_SIGNING_SECRET
        value: ~
      - name: METRONOME_SECRET_KEY
        value: ~
