apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dataplaneWebserver.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    {{- include "dataplaneWebserver.labels" . | nindent 4 }}
spec:
  rules:
    - host: dataplane.{{ .Values.global.baseDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "dataplaneWebserver.fullname" . }}
                port:
                  number: 80
            path: /
            pathType: Prefix
