{{ if .Values.dataplaneWebserver.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataplaneWebserver.fullname" . }}
  labels:
    {{- include "dataplaneWebserver.labels" . | nindent 4 }}
  {{- with .Values.dataplaneWebserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
