{{ if .Values.cpReconciler.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cpReconciler.fullname" . }}
  labels:
    {{- include "cpReconciler.labels" . | nindent 4 }}
  {{- with .Values.cpReconciler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
