{{ if .Values.temboUI.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temboUI.fullname" . }}
  labels:
    {{- include "temboUI.labels" . | nindent 4 }}
  {{- with .Values.temboUI.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
