apiVersion: v1
kind: Service
metadata:
  name: {{ include "temboUI.fullname" . }}
  labels:
    {{- include "temboUI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.temboUI.service.type }}
  ports:
    - port: {{ .Values.temboUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "temboUI.selectorLabels" . | nindent 4 }}
