# Default values for Tembo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

conductor:
  logLevel: info

  replicas: 1

  podMonitor:
    enabled: false
    port: http
    path: /metrics

  externalSecrets:
    refreshInterval: "5m"
    parameterStore:
      name: "secret-store-parameter-store"
      kind: ClusterSecretStore
    secretName: ~
    secretRegex: ~

  serviceMonitors:
    coredb:
      enabled: false

  image:
    repository: quay.io/coredb/conductor
    tag: "latest"
    pullPolicy: IfNotPresent

  # We should reconfigure the defaults
  # once we have more information about this
  # workload in practice.
  resources:
    limits:
      cpu: 1
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  serviceAccount:
    annotations: {}
    # Defaults to match name of deployment,
    # when this is set to empty string.
    name: ""

  imagePullSecrets: []
  nameOverride: conductor
  fullnameOverride: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env: {}
