apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conductor.fullname" . }}
  labels:
    {{- include "conductor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.conductor.replicas }}
  selector:
    matchLabels:
      {{- include "conductor.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.conductor.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "conductor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.conductor.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "conductor.fullname" . }}
      securityContext:
        {{- toYaml .Values.conductor.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
          - ./usr/local/bin/conductor
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: PG_CONN_URL
            valueFrom:
              secretKeyRef:
                name: data-plane
                key: _data-plane_postgres_connection_string
          - name: CONDUCTOR_ENABLED
            value: "true"
          - name: WATCHER_ENABLED
            value: "false"
          - name: RUST_LOG
            value: {{ .Values.conductor.logLevel }}
          {{- if .Values.conductor.env }}{{ .Values.conductor.env | default list | toYaml | nindent 10 }}{{- end }}
          securityContext:
            {{- toYaml .Values.conductor.securityContext | nindent 12 }}
          image: "{{ .Values.conductor.image.repository }}:{{ .Values.conductor.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.conductor.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: "/health/lively"
              port: http
          readinessProbe:
            httpGet:
              path: "/health/lively"
              port: http
          resources:
            {{- toYaml .Values.conductor.resources | nindent 12 }}
      {{- with .Values.conductor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.conductor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.conductor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
