apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-enc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
mountOptions:
  - discard # this might enable UNMAP / TRIM at the block storage layer
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
  fstype: "ext4"
  type: "gp3"
