apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cpWebserver.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    {{- include "cpWebserver.labels" . | nindent 4 }}
spec:
  rules:
    - host: api.{{ .Values.global.baseDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "cpWebserver.fullname" . }}
                port:
                  number: 80
            path: /
            pathType: Prefix
