apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpWebserver.fullname" . }}
  labels:
    {{- include "cpWebserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cpWebserver.service.type }}
  ports:
    - port: {{ .Values.cpWebserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cpWebserver.selectorLabels" . | nindent 4 }}
