apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cpWebserver.fullname" . }}
  labels:
    {{- include "cpWebserver.labels" . | nindent 4 }}
  {{- with .Values.cpWebserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
