apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cpService.fullname" . }}
  labels:
    {{- include "cpService.labels" . | nindent 4 }}
  {{- with .Values.cpService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
