apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpService.fullname" . }}
  labels:
    {{- include "cpService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cpService.service.type }}
  ports:
    - port: {{ .Values.cpService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cpService.selectorLabels" . | nindent 4 }}
